#zuul 路由配置可以省略，缺省以服务 id 作为访问路径
spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.85.131
    port: 5672
    username: admin
    password: admin
  sleuth:
    sampler:
      probability: 1
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true
#需要开启重试，默认不开启
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
  #zuul + hystrix 短路                  降低 hystrix 超时时间，以便测试降级
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
#暴露 hystrix.stream 监控端点                     zuul 已经包含 actuator 依赖
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream